resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: beta-backend

- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

shared:
- params: &modify-terraforming-aws-dns-params
    GCP_DNS_PROJECT_ID: ((cf_infra_gcp_project_id))
    GCP_DNS_SERVICE_ACCOUNT_EMAIL: ((cf_infra_gcp_service_account_email))
    GCP_DNS_SERVICE_ACCOUNT_KEY: ((cf_infra_gcp_service_account_key))
    GCP_DNS_ZONE_NAME: infrastructure
    GCP_DNS_SUFFIX: aws.infrastructure.cf-app.com
    GCP_DNS_RECORD_TTL: 60

- params: &om-creds
    OM_USERNAME: ((om.username))
    OM_PASSWORD: ((om.password))

resources:
- name: terraforming-aws
  type: git
  source:
    branch: master
    uri: git@github.com:pivotal-cf/terraforming-aws.git
    private_key: ((cf_infra_bot_github_user.private_key))

- name: env-state-aws
  type: terraform
  source:
    backend_type: gcs
    backend_config:
      bucket: infra-tf-states
      prefix: aws
      region: us-central1
      credentials: |
        {{cf_infra_gcp_service_account_key_for_terraform}}
    vars:
      region: us-west-1
      access_key: ((aws_access_key_id))
      secret_key: ((aws_secret_access_key))
      ssl_cert: ((ssl_cert.certificate))
      ssl_private_key: ((ssl_cert.private_key))
      availability_zones: ["us-west-1a", "us-west-1c"]
      ops_manager_ami: ami-0a073a805412627b2
      rds_instance_count: 0
      dns_suffix: aws.infrastructure.cf-app.com

- name: infrastructure-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/infrastructure-ci.git

- name: pcf-releng-ci
  type: git
  source:
    uri: git@github.com:pivotal-cf/pcf-releng-ci.git
    private_key: ((cf_infra_bot_github_user.private_key))
    ignore_paths:
    - pipelines
    - ci_screen

- name: pks
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: pivotal-container-service
    product_version: ^\d+\.\d+\.\d+
    sort_by: semver

- name: srt
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: elastic-runtime
    product_version: ^\d+\.\d+\.\d+
    sort_by: semver

jobs:
- name: deploy-pks
  serial: true
  public: false
  plan:
  - aggregate:
    - get: terraforming-aws
      trigger: true
    - get: ci
      resource: infrastructure-ci
    - get: pcf-releng-ci
    - get: pks
  - do:
    - put: env-state-aws
      params:
        env_name: terraforming-aws-pks
        terraform_source: terraforming-aws/terraforming-pks
        delete_on_failure: true
    - task: add-dns
      file: ci/scripts/common/manage-gcp-dns/task-terraforming.yml
      params:
        <<: *modify-terraforming-aws-dns-params
        ACTION: add
      input_mapping:
        env-state: env-state-aws
    - task: check-dns
      file: pcf-releng-ci/tasks/configuration/check-dns/task.yml
      input_mapping:
        terraform-state: env-state-aws
      timeout: 2m
    - task: configure-director
      file: ci/scripts/terraforming/configure-director/task.yml
      params:
        <<: *om-creds
        TEMPLATE_PATH: director-config-template/ci/assets/template/director-config.yml
      input_mapping:
        env-state: env-state-aws
        director-config-template: terraforming-aws
    - task: download-stemcell
      file: pcf-releng-ci/tasks/configuration/download-pivnet-stemcell/task.yml
      input_mapping:
        ert-product: pks
      params:
        IAAS_TYPE: aws
        PIVNET_TOKEN: ((pivnet_token))
    - task: upload-configure-stage-pks
      file: ci/scripts/terraforming/upload-configure-stage/task.yml
      params:
        <<: *om-creds
        PRODUCT_NAME: pivotal-container-service
        PRODUCT_CONFIG_TEMPLATE: ci/assets/template/pks-config.yml
      input_mapping:
        env-state: env-state-aws
        product: pks
        product-config-repo: terraforming-aws
    - task: apply-changes
      file: ci/scripts/terraforming/apply-changes/task.yml
      params:
        <<: *om-creds
      input_mapping:
        env-state: env-state-aws
    ensure:
      do:
      - task: delete-installation
        file: pcf-releng-ci/tasks/environment/delete-installation/task.yml
        params:
          OPSMAN_USERNAME: ((om.username))
          OPSMAN_PASSWORD: ((om.password))
          OPSMAN_URL_SUFFIX: aws.infrastructure.cf-app.com
        input_mapping:
          environment: env-state-aws
      - aggregate:
        - task: remove-dns
          file: ci/scripts/common/manage-gcp-dns/task-terraforming.yml
          params:
            <<: *modify-terraforming-aws-dns-params
            ACTION: remove
          input_mapping:
            env-state: env-state-aws
        - put: env-state-aws
          params:
            env_name: terraforming-aws-pks
            terraform_source: terraforming-aws/terraforming-pks
            delete_on_failure: true
            action: destroy
          get_params:
            action: destroy

- name: deploy-pas
  serial: true
  public: false
  plan:
  - aggregate:
    - get: terraforming-aws
      trigger: true
    - get: ci
      resource: infrastructure-ci
    - get: pcf-releng-ci
    - get: srt
      params:
        globs:
        - srt-*.pivotal
  - do:
    - put: env-state-aws
      params:
        env_name: terraforming-aws-pas
        terraform_source: terraforming-aws/terraforming-pas
        delete_on_failure: true
    - task: add-dns
      file: ci/scripts/common/manage-gcp-dns/task-terraforming.yml
      params:
        <<: *modify-terraforming-aws-dns-params
        ACTION: add
      input_mapping:
        env-state: env-state-aws
    - task: check-dns
      file: pcf-releng-ci/tasks/configuration/check-dns/task.yml
      input_mapping:
        terraform-state: env-state-aws
      timeout: 2m
    - task: configure-director
      file: ci/scripts/terraforming/configure-director/task.yml
      params:
        <<: *om-creds
        TEMPLATE_PATH: director-config-template/ci/assets/template/director-config.yml
      input_mapping:
        env-state: env-state-aws
        director-config-template: terraforming-aws
    - task: download-stemcell
      file: pcf-releng-ci/tasks/configuration/download-pivnet-stemcell/task.yml
      input_mapping:
        ert-product: srt
      params:
        IAAS_TYPE: aws
        PIVNET_TOKEN: ((pivnet_token))
    - task: upload-configure-stage-pas
      file: ci/scripts/terraforming/upload-configure-stage/task.yml
      params:
        <<: *om-creds
        PRODUCT_NAME: cf
        PRODUCT_CONFIG_TEMPLATE: ci/assets/template/srt-config.yml
      input_mapping:
        env-state: env-state-aws
        product: srt
        product-config-repo: terraforming-aws
    - task: apply-changes
      file: ci/scripts/terraforming/apply-changes/task.yml
      params:
        <<: *om-creds
        IGNORE_WARNINGS: true
      input_mapping:
        env-state: env-state-aws
    ensure:
      do:
      - task: delete-installation
        file: pcf-releng-ci/tasks/environment/delete-installation/task.yml
        params:
          OPSMAN_USERNAME: ((om.username))
          OPSMAN_PASSWORD: ((om.password))
          OPSMAN_URL_SUFFIX: aws.infrastructure.cf-app.com
        input_mapping:
          environment: env-state-aws
      - aggregate:
        - task: remove-dns
          file: ci/scripts/common/manage-gcp-dns/task-terraforming.yml
          params:
            <<: *modify-terraforming-aws-dns-params
            ACTION: remove
          input_mapping:
            env-state: env-state-aws
        - put: env-state-aws
          params:
            env_name: terraforming-aws-pas
            terraform_source: terraforming-aws/terraforming-pas
            delete_on_failure: true
            action: destroy
          get_params:
            action: destroy
